<a href="https://colab.research.google.com/github/Tikaanggrn/UTS_MACHINE_LEARNING2023-2024/blob/main/JAWABAN_UTS_MACHINE_LEARNING.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.impute import SimpleImputer
from sklearn.metrics import classification_report, silhouette_score
from sklearn.model_selection import train_test_split
from matplotlib import pyplot as plt
from sklearn import tree
from kneed import KneeLocator
from sklearn.cluster import KMeans
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score

Soal No.2

In [36]:
# Memisahkan bagian atribut prediktor dengan label data menjadi dua variabel terpisah
url = "/content/mobileprice_modified.csv"
data = pd.read_csv(url)

# Memisahkan atribut prediktor (fitur) dari label data
X = data.drop(columns=['price_range'])
y = data['price_range']

In [43]:
# Menangani missing values dengan SimpleImputer (strategi: mean)
imputer = SimpleImputer(strategy='mean')
X_imputed = imputer.fit_transform(X)

In [41]:
# Menerapkan StandardScaler untuk standarisasi atribut prediktor
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_imputed)

In [42]:
# Menampilkan statistik deskriptif sebelum preprocessing
print("Statistik Deskriptif Sebelum Preprocessing:")
print(pd.DataFrame(X, columns=data.columns.drop('price_range')).describe())

# Menampilkan statistik deskriptif setelah pengisian Missing Values dan standarisasi
print("\nStatistik Deskriptif Setelah Pengisian Missing Values dan Standarisasi:")
print(pd.DataFrame(X_scaled, columns=data.columns.drop('price_range')).describe())

Statistik Deskriptif Sebelum Preprocessing:
       battery_power       blue  clock_speed     dual_sim           fc  \
count    1990.000000  2000.0000  2000.000000  2000.000000  2000.000000   
mean     1237.867839     0.4950     1.522250     0.509500     4.309500   
std       439.676025     0.5001     0.816004     0.500035     4.341444   
min       501.000000     0.0000     0.500000     0.000000     0.000000   
25%       850.250000     0.0000     0.700000     0.000000     1.000000   
50%      1225.000000     0.0000     1.500000     1.000000     3.000000   
75%      1615.000000     1.0000     2.200000     1.000000     7.000000   
max      1998.000000     1.0000     3.000000     1.000000    19.000000   

            four_g   int_memory        m_dep    mobile_wt      n_cores  \
count  2000.000000  1990.000000  2000.000000  1990.000000  2000.000000   
mean      0.521500    31.987940     0.501750   140.344221     4.520500   
std       0.499662    18.136427     0.288416    35.407114     2.287

Soal No.3

In [49]:
# Memisahkan atribut prediktor (X_scaled) dari label data (y)
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.15, random_state=17)

In [50]:
# Inisialisasi model Decision Tree
decision_tree = DecisionTreeClassifier(random_state=17)

# Latih model pada data pelatihan
decision_tree.fit(X_train, y_train)


DecisionTreeClassifier(random_state=17)

In [51]:

#Melakukan prediksi pada data pengujian
y_pred = decision_tree.predict(X_test)

In [52]:
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

# Display results
print("Accuracy:", accuracy)
print("Confusion Matrix:\n", conf_matrix)
print("Classification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.8566666666666667
Confusion Matrix:
 [[66  8  0  0]
 [ 7 61  5  0]
 [ 1  8 63  4]
 [ 0  0 10 67]]
Classification Report:
               precision    recall  f1-score   support

           0       0.89      0.89      0.89        74
           1       0.79      0.84      0.81        73
           2       0.81      0.83      0.82        76
           3       0.94      0.87      0.91        77

    accuracy                           0.86       300
   macro avg       0.86      0.86      0.86       300
weighted avg       0.86      0.86      0.86       300



Soal No.4

In [29]:
# Inisialisasi model K-Means dengan jumlah cluster yang diinginkan
kmeans = KMeans(n_clusters=4, random_state=42)
kmeans.fit(X_scaled)


KMeans(n_clusters=4, random_state=42)

In [30]:
# Melakukan prediksi cluster pada data
cluster_labels = kmeans.predict(X_scaled)


In [31]:
# Mendapatkan label cluster untuk setiap sampel
cluster_labels = kmeans.labels_

In [53]:
silhouette_avg = silhouette_score(X_scaled, cluster_labels)

print("Silhouette Score:", silhouette_avg)

Silhouette Score: 0.05746542779025056
